### PR TITLE
Move InfluxDBStore into experimental subpackage; hide Dashboard for now.

### LINKED ISSUE #150: 'appdash serve': should use InfluxDBStore instead of MemoryStore by default
GET /dashboard/data?start=0&end=72: error: handler panic

runtime error: invalid memory address or nil pointer dereference

goroutine 22 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        C:/Go/src/runtime/debug/stack.go:24 +0x87
sourcegraph.com/sourcegraph/appdash/traceapp.handlerFunc.ServeHTTP.func1(0x16a6ff0, 0xc08219f860, 0xc0824d89a0)
        E:/RDLL/Golang/src/sourcegraph.com/sourcegraph/appdash/traceapp/handler.go:18 +0x5a
panic(0xa95e60, 0xc082008060)
        C:/Go/src/runtime/panic.go:426 +0x4f7
sourcegraph.com/sourcegraph/appdash/traceapp.(*App).serveDashboardData(0xc08200fa90, 0x16a7070, 0xc082194000, 0xc0824d89
a0, 0x0, 0x0)
        E:/RDLL/Golang/src/sourcegraph.com/sourcegraph/appdash/traceapp/dashboard.go:60 +0x295
sourcegraph.com/sourcegraph/appdash/traceapp.(*App).(sourcegraph.com/sourcegraph/appdash/traceapp.serveDashboardData)-fm
(0x16a7070, 0xc082194000, 0xc0824d89a0, 0x0, 0x0)
        E:/RDLL/Golang/src/sourcegraph.com/sourcegraph/appdash/traceapp/app.go:65 +0x53
sourcegraph.com/sourcegraph/appdash/traceapp.handlerFunc.ServeHTTP(0xc08215a640, 0x16a6ff0, 0xc08219f860, 0xc0824d89a0)
        E:/RDLL/Golang/src/sourcegraph.com/sourcegraph/appdash/traceapp/handler.go:22 +0xbf
github.com/gorilla/mux.(*Router).ServeHTTP(0xc08200f220, 0x16a6ff0, 0xc08219f860, 0xc0824d89a0)
        E:/RDLL/Golang/src/github.com/gorilla/mux/mux.go:103 +0x277
sourcegraph.com/sourcegraph/appdash/traceapp.(*App).ServeHTTP(0xc08200fa90, 0x16a6ff0, 0xc08219f860, 0xc0824d89a0)
        E:/RDLL/Golang/src/sourcegraph.com/sourcegraph/appdash/traceapp/app.go:76 +0x4c
net/http.serverHandler.ServeHTTP(0xc0820b3080, 0x16a6ff0, 0xc08219f860, 0xc0824d89a0)
        C:/Go/src/net/http/server.go:2081 +0x1a5
net/http.(*conn).serve(0xc0821ac980)
        C:/Go/src/net/http/server.go:1472 +0xf35
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2137 +0x455

Golang 1.6
Windows 10
PowerShell

### LINKED ISSUE #163: Libraries shouldn't vendor code or leak vendored types
The top-level appdash package is vendoring a bunch of libraries, including InfluxDB. Since the appdash package is a library, and not a command, it shouldn't vendor libraries. Vendoring is the sole responsibility of the project owner. For example, it would be fine for appdash/cmd/appdash to vendor the libraries it needs.

The problem with libraries that vendor code is that one dependency might be introduced with different versions to the final binary. This results in two possible symptoms. 

1. a library might affect global state. A DB driver, for example, might register itself with database/sql. If two versions of the same driver do this, it causes problems.
2. The package might be leaking vendored types. In the case of appdash, that's for example the influxDBServer.Config type. The type vendored in appdash will be different from the type I vendored myself in my project.

Now, it's of course possible for me to pull your vendored libs into my vendor directory, and delete yours. However that means that I'm not just tracking your repository anymore, but that I am maintaining a patched version of it. This creates a maintenance burden for me.

### PR DESCRIPTION
**Pull request by slimsag**
We've seen that InfluxDBStore hasn't lived up to our expectations, and have been encountering performance problems (particularly RAM usage problems) with it. It has been the source of a great amount of instability within Appdash, and while it's likely to improve in the future, the current plan is to move it into an experimental subpackage and potentially pick it back up in the future (though there are no current plans to do so).

- Fix `appdash serve` (assets not served properly)
- Do not display/serve Dashboard page except when using InfluxDBStore (not the default).
- Move InfluxDBStore into experimental subpackage.
- Fix #150
- FIx #163 

Users will need to update according to the following table:

| Before                            | After                           |
|-----------------------------------|---------------------------------|
| `appdash.InfluxDBAdminUser`       | `influxdbstore.AdminUser`       |
| `appdash.InfluxDBRetentionPolicy` | `influxdbstore.RetentionPolicy` |
| `appdash.InfluxDBConfig`          | `influxdbstore.Config`          |
| `appdash.NewInfluxDBConfig`       | `influxdbstore.NewConfig`       |
| `appdash.NewInfluxDBStore`        | `influxdbstore.New`             |
| `appdash.InfluxDBStore`           | `influxdbstore.Store`           |

### CODE REVIEW

File: event.go [hunk 1]
```diff
@@ -148,14 +148,14 @@ func UnmarshalEvents(anns Annotations, events *[]Event) error {
 	return nil
 }
 
-// A spanName event sets a span's name.
-type spanName struct{ Name string }
+// A SpanNameEvent event sets a span's name.
+type SpanNameEvent struct{ Name string }
```
Comment (keegancsmith) [inline event.go]:
```
rename+expose s/spanName/SpanEventEvent/g
expose s/schemaPrefix/SchemaPrefix/g
```
not really clear to me why this is necessary when just viewing the commit and commit message. Although my guess is it has something to do with moving the influx store (haven't searched looked at all the commits just yet)?

**Comment by keegancsmith** [comment]
glad to see the removal of vendor!

also LGTM
